### ISSUE TITLE
Prototyping example

### ISSUE THREAD

**Issue by Kaszaq** [miroapp/app-examples#1]
Hello,

Can you provide a small example on how to use prototyping example? Whatever I do I just end up with black frame without a way out of it. I understand this is an example and doesn't need to be perfect so I would like to know what is the intended flow? What to click and do in order to see the functionality of this example.

Thanks

**Comment by BobMoonbird** [comment]
Hi Michal! Your old friend Boris here.
I was just going to make a demo for you, and found out that we yet need to fix a couple of things.
I would expect some changes (and a demo gif) next week

**Comment by pltnkv** [comment]
Hello Michal. We have fixed this example and added a description.
https://github.com/miroapp/app-examples/tree/master/prototyping
You can see GIF or install the plugin and see how it works.
