### ISSUE TITLE
openModal ignores height when it is lower than the screen size

### ISSUE THREAD

**Issue by Kaszaq** [miroapp/app-examples#10]
When screen size is changed to 200 px, then when opening a modal it will be scaled down to fit into 200 px even when the value requested is higher ie 600. 

This method from SDK seem to work differently to plugins like Jira plugin where it somehow enforces to not be scaled down [ie its modal is not affected by screen size].

Expected behaviour is to have modal set to the size that is provided or allow for scrolling.

**Comment by pltnkv** [comment]
@Kaszaq Thank you for the feedback. We will reevaluate the logic behind modal window resizing. May be will add an option like:
`openModal('modal.html', {resizable: true})`
