### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JEflyer** [miroapp/app-examples#100]
When making a connector between two items you should be able to choose where the connector starts & ends on the items.

I've found that when making a connector between items it doesn't always place right so being able to choose would be a nice feature. 
Thoughts?

**Comment by marcospinello** [comment]
Hi @JEflyer, thank you for using the Miro Developer Platform to build on top of Miro boards.

If you're using the Web SDK, you can set start and end terminal points of the connector line with [`start`](https://developers.miro.com/docs/connector_connector-1#start) and [`end`](https://developers.miro.com/docs/connector_connector-1#end).

You can find a [complete copy-paste code example for the Web SDK here](https://developers.miro.com/docs/connector_connector-1).

If you're using the REST API, you can set the `x` and `y` coordinates of the start and end terminal points of the connector line with `startItem.position` and `endItem.position`: you can [check and try out the functionality here](https://developers.miro.com/reference/create-connector).
