### ISSUE TITLE
A client must have at least one registered redirect URL

### ISSUE THREAD

**Issue by coursewarefactory** [miroapp/app-examples#113]
Hello, I was trying to launch nextjs-full-stack app example, and I am getting this error after start `yarn dev`

**Comment by janza** [comment]
Hi @coursewarefactory, did you add the redirect URL to your app settings? 

You can do this in [your apps](https://miro.com/app/settings/user-profile/apps) page: 
Select the app that you created and under the _Redirect URI for OAuth2.0_ section add the following redirect URL: `http://localhost:3000/api/redirect/`.
