### ISSUE TITLE
Miro uikit returning not found

### ISSUE THREAD

**Issue by rosselton** [miroapp/app-examples#15]
I've installed the 'layers' code as a web widget to my dev team board and the link to https://miro.com/app/static/miro.uikit.css is returning 404.

It's called in the sidebar.html file:

```<link rel="stylesheet" type="text/css" href="https://miro.com/app/static/miro.uikit.css">```

Thanks

**Comment by ahmedelgabri** [comment]
Hi @rosselton,

Sorry for the late reply, you can find the correct URL here https://developers.miro.com/docs/component-demo

We are working on improving the examples in this repo to avoid all of these issues in the future.
