### ISSUE TITLE
sample-app not running with npm start

### ISSUE THREAD

**Issue by rosselton** [miroapp/app-examples#16]
I'm trying to run the sample-app code following the README instructions. However 'npm run start' fails with the following error:

```> wh@0.0.0 start C:\Users\nro25\code\miro-examples\app-examples\sample-app```
```> ./node_modules/nodemon/bin/nodemon.js ./src/app.js -e js,html```

```'.' is not recognized as an internal or external command```

In my package.json file

```
 "scripts": {
    "start": "./node_modules/nodemon/bin/nodemon.js ./src/app.js -e js,html",
    "ngrok": "./node_modules/ngrok/bin/ngrok http 3000"
  }
```
Any suggestions? Thanks

**Comment by ahmedelgabri** [comment]
@rosselton can you please try to make these edits & run `npm start` again?

```diff
   "scripts": {
-    "start": "./node_modules/nodemon/bin/nodemon.js src/app.js -e js,html",
-    "ngrok": "./node_modules/ngrok/bin/ngrok http 3000"
+    "start": "nodemon ./src/app.js -e js,html",
+    "ngrok": "ngrok http 3000"
   },
```

**Comment by rosselton** [comment]
> @rosselton can you please try to make these edits & run `npm start` again?
> 
> ```diff
>    "scripts": {
> -    "start": "./node_modules/nodemon/bin/nodemon.js src/app.js -e js,html",
> -    "ngrok": "./node_modules/ngrok/bin/ngrok http 3000"
> +    "start": "nodemon src/app.js -e js,html",
> +    "ngrok": "ngrok http 3000"
>    },
> ```

Yes, that now runs - many thanks!
