### ISSUE TITLE
READ me improvements

### ISSUE THREAD

**Issue by erikacamilleri** [miroapp/app-examples#24]
Hello, 

Really interested in trying out Prototyping in my miro board. I managed to follow the instructions to the letter save the last one:

"Get https url from ngrok and paste it in iframe url in your app settings."

I am not sure what this means. Do you think it could be explained better? I apologise if it is too basic. Also, I am on the free miro plan. Could it be I need to upgrade to be able to use your plugin?

Thanks.

**Comment by ahmedelgabri** [comment]
Hi @erikacamilleri,

No need to appologize, we are aware that our documentation is not perfect & we are already working on evaluating it & improving it. 

I assume that you already created a dev team account, created an app on Miro & followed all the steps until this step (feel free to correct me if I'm wrong)

> "Get https url from ngrok and paste it in iframe url in your app settings."

1. When you run `npx ngrok http 8081` you should see something like this in your terminal

```
ngrok by @inconshreveable            (Ctl+C to quit)

ngrok does not support a dynamic, color terminal UI on solaris.
Access the web interface for connection and tunnel status.

Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
```

2. You will need to visit `http://127.0.0.1:4040` in your browser (_Tip: some terminal allows you to <kbd>CTRL</kbd>/<kbd>CMD</kbd>+Click on URLs to open them in your browser_)

3. When you visit this URL you should see something like this (_Keep in mind that the URLs should be different every time you run the `npx ngrok http 8081` command_)

```
To get started, make a request to one of your tunnel URLs
 - http://*********.ngrok.io
 - https://*********.ngrok.io
```

4. You will need to copy the second URL that starts `https`& add it to this section in your app settings
![Screenshot 2020-11-18 at 12 14 20](https://user-images.githubusercontent.com/63876/99524103-3f60ac00-2998-11eb-883b-45277f82c508.png)

I hope this answers your question & please let me know if something was not clear.

**Comment by erikacamilleri** [comment]
@ahmedelgabri magic. Thanks a lot!

**Comment by statsconchris** [comment]
What if the local server doesnt have a UI... curl doesn't work and tunneling also fails
