### ISSUE TITLE
No scopes included in response - Sample app

### ISSUE THREAD

**Issue by ClydeDz** [miroapp/app-examples#26]
Hi,

I'm using the [sample app](https://github.com/miroapp/app-examples/tree/master/sample-app) as the codebase and have included code from the [drag and drop](https://github.com/miroapp/app-examples/tree/master/drag-and-drop) app to insert an image into the board. However, I'm getting the following error:   
```
Uncaught (in promise) Error while command execution: Method 'create' requires scope 'boards:write'
```
In the app configuration, I've clicked these checkboxes and then the button.  
![image](https://user-images.githubusercontent.com/13506613/101592712-99163c80-3a53-11eb-984c-d36608d73919.png)

I've also tried clicking on the Install app link from the app itself.
![image](https://user-images.githubusercontent.com/13506613/101592796-b5b27480-3a53-11eb-94a2-8d6a499ca587.png)

However, when I check the console, no scopes are included in the response. 
![image](https://user-images.githubusercontent.com/13506613/101592649-83087c00-3a53-11eb-939e-1fcff9a1ccbb.png)

How do I request scopes while getting an access token? Do I need to include additional query string parameters? 

Any help will be much appreciated.
Thanks!

**Comment by ahmedelgabri** [comment]
Hi @ClydeDz,

I'm unable to reproduce this error, it works fine with me & I was getting the scopes back in the response. I wonder if you can maybe share the repo that you are working on or a simplified version of it. This will allow us to help you more.

**Comment by ClydeDz** [comment]
Hi @ahmedelgabri, thanks for the response. Here's the [GitHub repository](https://github.com/ClydeDz/miro-dev-sample) with the files I was working with.

**Comment by ahmedelgabri** [comment]
I have created a new app from that repo, tested it & everything is working fine with me, here is what I did:

- I added an `.env` file based on the [`.env.example`](https://github.com/miroapp/app-examples/blob/cdbad6fe67935e8d66b1ec3a53c851f310ba7680/sample-app/.env.example) file here, you will need to fill in, `CLIENT_ID`, `CLIENT_SECRET` & `BASE_URL` (_if you are using ngrok then you might need to change the URL every time you run `npm run ngrok`, but if you are hosting the apps somewhere then you need to point to that URL_)

- In app settings page, I added a redirect URL, which is the `BASE_URL/oauth` so for example if you are using ngrok should look something like this `https://------------.ngrok.io/oauth`

<img width="619" alt="Screenshot 2020-12-10 at 10 32 33" src="https://user-images.githubusercontent.com/63876/101753586-1e8d0180-3ad3-11eb-9cbd-51c5364beb27.png">

- Also in app settings I added the URL for the plugin URL in your case it's `BASE_URL/static/web-plugin` so for example `https://------------.ngrok.io/static/web-plugin`

<img width="423" alt="Screenshot 2020-12-10 at 10 35 26" src="https://user-images.githubusercontent.com/63876/101754126-ad9a1980-3ad3-11eb-9783-e7828236b44d.png">

**Comment by ClydeDz** [comment]
Thanks for checking this out, @ahmedelgabri. I did the same steps as you mentioned.

Were you able to add the image to your miro board? Just to be clear - the app itself is working, but I cannot add the image to my board.

In the steps listed above, you didn't explicitly mention anything about `boards:write` scope, then how did the response contain that scope?

**Comment by ahmedelgabri** [comment]
> Were you able to add the image to your miro board? Just to be clear - the app itself is working, but I cannot add the image to my board.

Yes everything worked fine for me.



> In the steps listed above, you didn't explicitly mention anything about `boards:write` scope, then how did the response contain that scope?

Sorry about that, I forgot to mention that I also had `board:read` & `board:write` scopes too.

**Comment by ClydeDz** [comment]
That's very interesting. I created a new app in Miro and did the steps again, and this time I'm getting back the scope. For some reason, the previous app that I was reusing didn't work (although everything configured correctly).
