### ISSUE TITLE
Does this run on frontend exclusively or it has a backend?

### ISSUE THREAD

**Issue by echatzikyriakidis** [miroapp/app-examples#262]
Hi everyone,

My question if this uses a backend component or if it runs completely in frontend because it could bypassed, since it is all js.

Does it uses a backend in Typescript that communicates with stripe for the payment and also the manage of user's Miro board? If there is indeed a backend component does it communicates with Miro after OAuth authentication, access token, etc?

Thanks

**Comment by horeaporutiu** [comment]
Hi @echatzikyriakidis 

I assume you are talking about the monetization with stripe app. It's using Next.js so each of the endpoints is listed after the /api directory. So if the server was running on localhost:3000, this [file](https://github.com/miroapp/app-examples/blob/main/examples/monetization-with-stripe/pages/api/payment-handler.ts) defines an endpoint for localhost:3000/payment-handler.

The storage mechanism is implemented in a very basic manner. It is not intended for production purposes but just a quick and easy way to get a very basic implementation of a paywall using Stripe to work. 

The app implements the OAuth flow on the /redirect endpoint which can be found in this [file](https://github.com/miroapp/app-examples/blob/main/examples/monetization-with-stripe/pages/api/redirect.ts).

Please let me know if you have further questions.

**Comment by echatzikyriakidis** [comment]
Hi @horeaporutiu !

So, from your answer what I am understanding is that the backend (Next.js) implements the OAuth authentication of the Miro user, and with this way the backend will be able to manage user's Miro board and also has a handler that Stripe will call whenever a payment is made. Right?

Thanks!

**Comment by horeaporutiu** [comment]
Hi @echatzikyriakidis 

Yes, exactly. You can see it is exchanging code for access token [here](https://github.com/miroapp/app-examples/blob/main/examples/monetization-with-stripe/pages/api/redirect.ts#L18).

You can also see a quick 30 second demo of what the app will look like if you configure it on your local machine here: https://github.com/miroapp/app-examples/tree/main/examples/monetization-with-stripe#-app-demo

The idea is that this app-example is aiming to help a developer implement a paywall. So to only enable certain features if a user has paid. 

In [these lines](https://github.com/miroapp/app-examples/blob/main/examples/monetization-with-stripe/pages/api/payment-handler.ts#L40-L54) it's checking if the checkout in Stripe was completed, and if it was then you can set in your storage that this userID has paid, so they have access to paid features. 

Let me know if you have further questions.

**Comment by echatzikyriakidis** [comment]
Thank you @horeaporutiu !

**Comment by horeaporutiu** [comment]
No problem @echatzikyriakidis. Closing this issue now but feel free to re open if you have other questions.
