### ISSUE TITLE
Is it possible I put text inside an image after drag and drop it?

### ISSUE THREAD

**Issue by felipeajc** [miroapp/app-examples#29]
I am trying to create this feature: I just want to drag and drop an image and insert a text inside the image, like in shapes. Is it possible to do? Could U help me pls? Thanks

**Comment by anthonyroux** [comment]
Hi @felipeajc,

Thanks for reaching out.
The [Image widget](https://developers.miro.com/docs/interface-iimagewidget) doesn't not have a text field like a [Shape](https://developers.miro.com/docs/interface-ishapewidget). You cannot add a text to an image the same way you can to a Shape. This is linked to Miro itself not the Web SDK.

A (dirty) way to do that could be to create a [Text](https://developers.miro.com/docs/interface-itextwidget) at the same coordinates than the image you create with the drag and drop and push to back the image to the text is on top (or bring the text to the front). For this you can use [bringForward](https://developers.miro.com/docs/interface-iboardwidgetscommands#section-bring-forward) or [sendBackward](https://developers.miro.com/docs/interface-iboardwidgetscommands#section-send-backward).

Hope it clarifies,
Anthony
