### ISSUE TITLE
miro.d.ts does not have requestAuthorization

### ISSUE THREAD

**Issue by miroo93** [miroapp/app-examples#31]
Hi,

We added [miro.d.ts](https://github.com/miroapp/app-examples/blob/master/miro.d.ts) as an npm dependency in our package.json which helps us quite a bit with developing our plugin with Typescript.

However, we are currently in the process of migrating from authorize to requestAuthorization [as described here](https://developers.miro.com/docs/miroauthorize) to prepare for the change coming up in July 1.

But so far that miro.d.ts hasn't been updated, and it does not have a definition for the requestAuthorization method.

Is that going to be added soon?

Thank you!

**Comment by ahmedelgabri** [comment]
@miroo93 sorry about that, I have updated `miro.d.ts` now.
