### ISSUE TITLE
Ngrok package does not work well in sample-app for windows 10.

### ISSUE THREAD

**Issue by JamesYang-7** [miroapp/app-examples#33]
In sample-app, I tried to run 'npm run ngrok' on both windows 10 and WSL2 Ubuntu 20.04, but all failed. I confirmed that the package was installed and not broken, but there were always some problems with ngrok. 
It seems better for windows developers to download .exe file from the official site of ngrok. I suggest to add this tip to readme.md.

**Comment by ahmedelgabri** [comment]
Hi @JamesYang-7, 

Thanks for this, I will try to check it later. But I'm curious to understand why do you want to try the `sample-app` instead of the `create-miro-app`, anything in particular? Do you need the server?

```
npx create-miro-app
```
