### ISSUE TITLE
Duplicated plugins [iframes]

### ISSUE THREAD

**Issue by Kaszaq** [miroapp/app-examples#6]
Hi,

I noticed that sometimes frames with plugins duplicate themselves. 
![image](https://user-images.githubusercontent.com/5243787/70280900-d3525b80-17b9-11ea-8447-f989ada91208.png)

Looks like some bug so letting you know.

Cheers

**Comment by pltnkv** [comment]
Thank you for reporting, it's a known issue. It's in our backlog
