### ISSUE TITLE
GitHub AppCards readme is a little confusing 

### ISSUE THREAD

**Issue by testworksau** [miroapp/app-examples#80]
Hi Team Miro 👋🏼 

I've been looking into spinning up the GitHub AppCards example, and am currently a touch confused as to what I need to do to get this up and running. The instructions say:

> add a .env file with the required environment variables (See section at bottom)

and [the section](https://github.com/miroapp/app-examples/tree/main/examples/github-appcards#required-environment-variables) has a list of required environment variables, but no indication of what I need to do to obtain them.

I'm not familiar with Vite or Supabase - is there a guide or similar that I can follow to set these things up and obtain the relevant values to populate the env vars with?

**Comment by marcospinello** [comment]
Hi @testworksau!

Thank you for submitting this issue, and apologies for the lack of clarity about the `.env` vars.
We logged a ticket to expand this section of the Readme to add the missing information and include examples.

In the meantime, can this commented code block get you unblocked?
If not, what else can we do to get you up and running asap?

For more information on Vite `.env` files: see https://vitejs.dev/guide/env-and-mode.html#env-files

```
# Generate an access token in GitHub, and enter the value here.
# To generate the access token go to https://github.com/settings/tokens
VITE_GH_ACCESS_TOKEN=

# Enter here the password for the database you created on in Supabase.
VITE_SUPABASE_PASSWORD=

# Enter here the URL of the Supabase database that the app uses for data persistence.
# For more information, see https://supabase.com/docs/guides/database
VITE_DATABASE_URL=

# Enter here the API key of the Supabase project with the database that the app uses for data persistence.
# For more information, see https://supabase.com/docs/guides/api#api-url-and-keys
VITE_DATABASE_PUBLIC_KEY=

# Enter here the base URL of the hosting servece your app is running on.
# If you're developing locally, it can be 'localhost' for example.
VITE_BASE_URL=

# Ignore this field, it's no longer necessary. We'll update the README accordingly.
VITE_MIRO_API_TOKEN=

# Enter here the client secret of your app.
# For more information, see
# https://developers.miro.com/docs/build-your-first-hello-world-app#step-4-configure-your-app-in-miro
MIRO_CLIENT_SECRET=

# Enter here the OAuth code grant flow redirect URI for your app.
# For more information, see:
# https://developers.miro.com/docs/getting-started-with-oauth
# https://developers.miro.com/reference/authorization-flow-for-expiring-access-tokens
MIRO_REDIRECT_URI=
```

**Comment by testworksau** [comment]
That's super helpful, thanks @marcospinello 🎉 

The only other thing I can think would be useful would be documenting the scope of the GH token; I assume it only requires the repo read / write access level?
