### ISSUE TITLE
Making a connection between sticky notes

### ISSUE THREAD

**Issue by JEflyer** [miroapp/app-examples#99]
I've been trying to make a connection between 2 notes using the Miro node js client but I am running into some error when trying to push the connection to the board.

The code I am trying to run.

const { MiroApi, Connector, StickyNoteItem } = require("@mirohq/miro-api")

require("dotenv").config()

const miroApi = new MiroApi(process.env.ACCESS_TOKEN)

//Removed my boardID for this issue
const boardID = ""

async function postStickyNote(x, y, id) {
    const board = await miroApi.getBoard(boardID)
    console.log(board)

    const stickyNote = new StickyNoteItem(miroApi, boardID, id, {
        type: "string",
        data: {
            content: "Hello World",
            shape: "rectangle",

        },
        style: {
            fillColor: "light_green",
            textAlign: "center",
            textAlignVertical: "bottom"
        },
        position: {
            x: x,
            y: y,
            relativeTo: "Anything can go  in here & it posts to the board anyways"
        }
    })

    await board.createStickyNoteItem(stickyNote)

    return stickyNote.id
}

async function start() {
    const board = await miroApi.getBoard(boardID)
    console.log(board)

    let id1 = await postStickyNote(-1000, 0, 1)
    let id2 = await postStickyNote(1000, 0, 2)

    const connection = new Connector(
        miroApi,
        boardID,
        "Connector-1", 
        {
            id: 3,
            startItem: {
                id: id1
            },
            endItem: {
                id: id2
            }
        }
    )

    await board.createConnector(connection)
}

start()

The error I am getting 

C:\Users\Admin\OneDrive\Desktop\jonny code\MiroTest\node_modules\@mirohq\miro-api\dist\api\apis.js:2292
        throw new HttpError(response, bodyAsJson, response.status);
              ^

HttpError: HTTP request failed
    at makeJsonRequest (C:\Users\Admin\OneDrive\Desktop\jonny code\MiroTest\node_modules\@mirohq\miro-api\dist\api\apis.js:2292:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MiroApi.createConnector (C:\Users\Admin\OneDrive\Desktop\jonny code\MiroTest\node_modules\@mirohq\miro-api\dist\api\apis.js:627:42)
    at async Board.createConnector (C:\Users\Admin\OneDrive\Desktop\jonny code\MiroTest\node_modules\@mirohq\miro-api\dist\highlevel\index.js:317:25)
    at async start (C:\Users\Admin\OneDrive\Desktop\jonny code\MiroTest\MakeConnection.js:58:5) {
  response: Response {
    size: 0,
    timeout: 15000,
    [Symbol(Body internals)]: {
      body: PassThrough {
        _readableState: ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          ended: true,
          endEmitted: true,
          reading: false,
          constructed: true,
          sync: false,
          needReadable: false,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          destroyed: true,
          errored: null,
          closed: true,
          closeEmitted: true,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: true,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
          prefinish: [Function: prefinish],
          error: [ [Function (anonymous)], [Function (anonymous)] ],
          data: [Function (anonymous)],
          end: [Function (anonymous)]
        },
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: true,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          destroyed: true,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: true,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          errored: null,
          closed: true,
          closeEmitted: true,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: true,
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      disturbed: true,
      error: null
    },
    [Symbol(Response internals)]: {
      url: 'https://api.miro.com/v2/boards/<ID Removed For Issue>/connectors',
      status: 400,
      statusText: 'Bad Request',
      headers: Headers {
        [Symbol(map)]: [Object: null prototype] {
          'content-type': [ 'application/json' ],
          'content-length': [ '376' ],
          connection: [ 'close' ],
          date: [ 'Sun, 30 Oct 2022 23:51:13 GMT' ],
          server: [ 'nginx' ],
          'set-cookie': [
            'AWSALBTG=M/pMDthwegXAob8Jt2xkjrTkv+0w/dAOYiK6VTH7aduh25VmMVjRU1tmY4ERmjEPKGqmE97/a4ffmqnOipwegJZkekx6aHJa9ZsiP/CpNgwYUahE+dPWaPJUkxKMt/FeWSPKYoYz47GY7YkNB/h7G+ZO6Af+jHkPAwp04PJQNufy; Expires=Sun, 06 Nov 2022 23:51:12 GMT; Path=/',
            'AWSALBTGCORS=M/pMDthwegXAob8Jt2xkjrTkv+0w/dAOYiK6VTH7aduh25VmMVjRU1tmY4ERmjEPKGqmE97/a4ffmqnOipwegJZkekx6aHJa9ZsiP/CpNgwYUahE+dPWaPJUkxKMt/FeWSPKYoYz47GY7YkNB/h7G+ZO6Af+jHkPAwp04PJQNufy; Expires=Sun, 06 Nov 2022 23:51:12 GMT; Path=/; SameSite=None; Secure'
          ],
          vary: [
            'Origin, Access-Control-Request-Method, Access-Control-Request-Headers'
          ],
          'content-security-policy': [ "default-src 'self'" ],
          'referrer-policy': [ 'no-referrer' ],
          'x-ratelimit-limit': [ '100000' ],
          'x-ratelimit-remaining': [ '99550' ],
          'x-ratelimit-reset': [ '1667173931' ],
          'x-request-id': [ '810eb201-42d7-431c-9762-759f9a6a91f7' ],
          'x-content-type-options': [ 'nosniff' ],
          'x-xss-protection': [ '1; mode=block' ],
          'cache-control': [
            'private, no-cache, no-store, no-transform, max-age=0, must-revalidate, proxy-revalidate'
          ],
          pragma: [ 'no-cache' ],
          expires: [ '0' ],
          'x-frame-options': [ 'DENY' ],
          'strict-transport-security': [ 'max-age=31536000' ],
          'x-cache': [ 'Error from cloudfront' ],
          via: [
            '1.1 68126347056de2d05be3dd362ccba986.cloudfront.net (CloudFront)'
          ],
          'x-amz-cf-pop': [ 'LHR50-C1' ],
          'x-amz-cf-id': [
            'PQ1cuhzi2ct27Ib3CUgC_UfkabQx2-3ICNQNyr73hpOPOsezJ3cTXA=='
          ]
        }
      },
      counter: 0
    }
  },
  body: {
    type: 'error',
    code: '3.0215',
    context: {
      boardId: '',
      validationErrors: [
        { code: '3.0209', message: 'Value 1 is not allowed' },
        { code: '3.0209', message: 'Value 2 is not allowed' }
      ]
    },
    message: 'Unable to complete operation because of the validation errors.',
    status: 400
  },
  statusCode: 400
}

Any help here would be appreciated, thankyou :)

**Comment by janza** [comment]
Hi @JEflyer, the issue is that the code is creating instances with ids manually using the `new` keyword, and not using the item ids returned from the server. 

The following should work for your case:
```
async function postStickyNote(x, y, id) {
  const board = await miroApi.getBoard(boardID)
  console.log(board)

  return await board.createStickyNoteItem({
    data: {
      content: "Hello World",
    },
    style: {
      fillColor: "light_green",
      textAlign: "center",
      textAlignVertical: "bottom"
    },
    position: {
      x: x,
      y: y,
    }
  })
}

async function start() {
  const board = await miroApi.getBoard(boardID)
  console.log(board)

  let note1 = await postStickyNote(-1000, 0)
  let note2 = await postStickyNote(1000, 0)

  await note1.connectTo(note2.id)

  // OR alternatively:
  // await board.createConnector({
  //   startItem: {
  //     id: note1
  //   },
  //   endItem: {
  //     id: note2
  //   }
  // })
}

start()

```

Hope this helps!

**Comment by JEflyer** [comment]
Sorry for taking so long to reply, yes this works thank you I appreciate the help!
